# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wdm < Formula
  desc "CLI para levantar entornos de desarrollo aislados por branch"
  homepage "https://github.com/sofiandreoli/worktree-dev-manager"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sofiandreoli/worktree-dev-manager/releases/download/v0.1.1/wdm_0.1.1_darwin_amd64.tar.gz"
      sha256 "207d15df62adc963148270885bb031af7a656883860ed87386d1c7d9ffc1cc41"

      define_method(:install) do
        bin.install "wdm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sofiandreoli/worktree-dev-manager/releases/download/v0.1.1/wdm_0.1.1_darwin_arm64.tar.gz"
      sha256 "6a456f07d7995783385be46ddb597dc61b67831fb2e4ef86aaf843990c353d13"

      define_method(:install) do
        bin.install "wdm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/worktree-dev-manager/releases/download/v0.1.1/wdm_0.1.1_linux_amd64.tar.gz"
      sha256 "78ad7e440c19af481a5fb307413205a33b98ed5b1a1b35fad5819b2f4bf30932"
      define_method(:install) do
        bin.install "wdm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/worktree-dev-manager/releases/download/v0.1.1/wdm_0.1.1_linux_arm64.tar.gz"
      sha256 "e26b9217d4535d483c9022b9f12ee60b098b9c3668b1067a9f0fc698f7e2c5b4"
      define_method(:install) do
        bin.install "wdm"
      end
    end
  end

  test do
    system "#{bin}/wdm", "--version"
  end
end
