# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wdm < Formula
  desc "CLI to spin up isolated per-branch dev environments with git worktrees"
  homepage "https://github.com/sofiandreoli/wdm-releases"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sofiandreoli/wdm-releases/releases/download/v0.1.4/wdm_0.1.4_darwin_amd64.tar.gz"
      sha256 "88722139e0220313d81bcee03914c3ead3e4194466619204500ff4c96af90447"

      define_method(:install) do
        bin.install "wdm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sofiandreoli/wdm-releases/releases/download/v0.1.4/wdm_0.1.4_darwin_arm64.tar.gz"
      sha256 "3f14e0e4659dd10dc6a1a2476c482996bdb8c34cd84e12e31f2d4fa802230376"

      define_method(:install) do
        bin.install "wdm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/wdm-releases/releases/download/v0.1.4/wdm_0.1.4_linux_amd64.tar.gz"
      sha256 "5ef822a692e89e55a7db81fc0365a3a981389317b3cae72ad8824649afdf5f50"
      define_method(:install) do
        bin.install "wdm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/wdm-releases/releases/download/v0.1.4/wdm_0.1.4_linux_arm64.tar.gz"
      sha256 "650b265ec5b575f8b4f981608fbd2adf1dbd34ebbc7a0b6d2dc3effa05643684"
      define_method(:install) do
        bin.install "wdm"
      end
    end
  end

  test do
    system "#{bin}/wdm", "--version"
  end
end
