# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wdm < Formula
  desc "CLI to spin up isolated per-branch dev environments with git worktrees"
  homepage "https://github.com/sofiandreoli/wdm-releases"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sofiandreoli/wdm-releases/releases/download/v0.1.6/wdm_0.1.6_darwin_amd64.tar.gz"
      sha256 "8a347061b5db94758bce7683d9018c3fae918331182875ff5d7192c36d384048"

      define_method(:install) do
        bin.install "wdm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sofiandreoli/wdm-releases/releases/download/v0.1.6/wdm_0.1.6_darwin_arm64.tar.gz"
      sha256 "358ea74693a2468e97df9613392bcde3c6c0b59f8d6056b93d923679e187a0de"

      define_method(:install) do
        bin.install "wdm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/wdm-releases/releases/download/v0.1.6/wdm_0.1.6_linux_amd64.tar.gz"
      sha256 "5bf896c00dddfe00d3f918e4861704b855ed9dfaa597a87a2ca6e79c33594755"
      define_method(:install) do
        bin.install "wdm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sofiandreoli/wdm-releases/releases/download/v0.1.6/wdm_0.1.6_linux_arm64.tar.gz"
      sha256 "07b169adb4b7ae3c4883652d0a6c7618591d6588a070dedde979c10f9610ba19"
      define_method(:install) do
        bin.install "wdm"
      end
    end
  end

  test do
    system "#{bin}/wdm", "--version"
  end
end
